[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.15.2"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[[constraint]]
  name = "github.com/nats-io/go-nats-streaming"
  version = "0.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/ribice/msv"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.2.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/vmihailenco/msgpack"
  version = "4.0.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
